spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:46273/railway
spring.datasource.username=root
spring.datasource.password=SpvVQlVExGUrIHliusWuBzeMFQjlsTqh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=${PORT:8081}